version: '3'
services:
  tsmc-storage_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tsmc-storage
    ports:
      - 5432:5432
    hostname: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tsmc-storage:
    build: ./app
    restart: always
    ports:
      - 8300:8300
    depends_on:
      - tsmc-storage_db

volumes:
  postgres-data: